name: Code formatting and linting checks

on:
  push:
    branches: [main]
    paths: ["**/*.lua"]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths: ["**/*.lua"]

jobs:
  format-check:
    name: Code formatting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Stylua formatter check
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
  lint-check:
    name: Code linting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Luacheck linter
        uses: lunarmodules/luacheck@v1
        with:
          args: .
